version: 2

jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - start:
          name: [Step] - Start
          command: echo Hello, world.

      - test:
          name: [Step] - Test
          command: ng test