version: 2

jobs:
  build:
    docker:
      - image: node:carbon-jessie

    steps:
      - checkout

      - run:
          name: Install Angular CLI
          command: npm install -g @angular/cli

      - run:
          name: Move to project folder
          command: ls -la

      - run:
          name: Test
          command: ng test