version: 2

jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Start
          command: echo Hello, world.

      - run:
          name: Test
          command: ng test